Adding in external files for configs.

diff --git a/package-scripts/puppet/postinst b/package-scripts/puppet/postinst
--- a/package-scripts/puppet/postinst
+++ b/package-scripts/puppet/postinst
@@ -1,16 +1,14 @@
 #!/bin/bash
 #
-# Perform necessary puppet setup steps
-# after package is installed.
+# Perform necessary puppet setup steps after package is installed.
 #
 
 PROGNAME=$(basename $0)
-INSTALLER_DIR="/opt/puppet"
+DEST_DIR="/opt/puppet"
 CONFIG_DIR="/etc/puppet"
 VAR_DIR="/var/lib/puppet"
 LOG_DIR="/var/log/puppet"
 PREFIX="/usr"
-PUPPET_GEM_DIR=`ls -dr ${INSTALLER_DIR}/embedded/lib/ruby/gems/*/gems/puppet-* | head -1`
 
 function error_exit
 {
@@ -18,11 +16,15 @@ function error_exit
   exit 1
 }
 
+# rm -f before ln -sf is required for solaris 9
+rm -f $PREFIX/bin/puppet
+rm -f $PREFIX/bin/facter
+
 #Link binaries
 ln -sf $INSTALLER_DIR/bin/puppet $PREFIX/bin || error_exit "Cannot link puppet to $PREFIX/bin"
 ln -sf $INSTALLER_DIR/bin/facter $PREFIX/bin || error_exit "Cannot link facter to $PREFIX/bin"
 
-# Create the "puppet" user
+# Create the "puppet" user if it does not already exist
 if ! getent passwd puppet > /dev/null; then
   adduser --quiet --system --group --home $VAR_DIR  \
     --no-create-home                                 \
@@ -30,43 +32,21 @@ if ! getent passwd puppet > /dev/null; then
     puppet
 fi
 
-# Set correct permissions and ownership for puppet directories
-if [ ! -d "$VAR_DIR" ]; then
-  mkdir -m 750 $VAR_DIR
-  chown puppet:puppet $VAR_DIR
-fi
+# Create puppet directories
+mkdir -m 750 -p $VAR_DIR || error_exit "Cannot create $VAR_DIR"
+mkdir -m 755 -p $VAR_DIR/state || error_exit "Cannot create $VAR_DIR/state"
+mkdir -m 750 -p $LOG_DIR || error_exit "Cannot create $LOG_DIR"
 
-if [ ! -d "$VAR_DIR/state" ]; then
-  mkdir -m 755 $VAR_DIR/state
-  chown puppet:puppet $VAR_DIR
-fi
+# Set correct ownership of puppet directories
+chown puppet:puppet $VAR_DIR || error_exit "Cannot change permissions of $VAR_DIR"
+chown puppet:puppet $VAR_DIR/state || error_exit "Cannot change permissions of $VAR_DIR/state"
+chown puppet:puppet $LOG_DIR || error_exit "Cannot change permissions of $LOG_DIR"
 
-if [ ! -d "$LOG_DIR" ]; then
-  mkdir -m 750 $LOG_DIR
-  chown puppet:puppet $LOG_DIR
-fi
-
-# Create config if it doesn't exist
-if [ ! -d "$CONFIG_DIR" ]; then
-  mkdir -m 755 $CONFIG_DIR
-fi
-
-# Copy in default configuration if none exists already (FIXME: support OS's other than Debian)
-if [ ! -e "$CONFIG_DIR"/puppet.conf ]; then
-  cp ${PUPPET_GEM_DIR}/ext/debian/puppet.conf ${CONFIG_DIR}/puppet.conf
-  chmod 644 ${CONFIG_DIR}/puppet.conf
-fi
-
-# Copy in init scripts if none exists already (FIXME: support OS's other than Debian)
+# TODO: Remove and put it in puppet-files
 if [ ! -e /etc/init.d/puppet ] ; then
+  PUPPET_GEM_DIR=`ls -dr ${DEST_DIR}/embedded/lib/ruby/gems/*/gems/puppet-* | head -1`
   cp ${PUPPET_GEM_DIR}/ext/debian/puppet.init /etc/init.d/puppet
   chmod 755 /etc/init.d/puppet
-fi
-
-# Copy in init script config if none exists already (FIXME: support OS's other than Debian)
-if [ ! -e /etc/default/puppet ] ; then
-  cp ${PUPPET_GEM_DIR}/ext/debian/puppet.default /etc/default/puppet
-  chmod 644 /etc/default/puppet
 fi
 
 echo "Thank you for installing puppet!"
